create or replace PACKAGE GARAGE AS

  /* TODO enter package declarations (types, exceptions, methods etc) here */
  FUNCTION UPDATE_LOG_NO_CHECK(
    P_CAR_ID IN NUMBER)
    RETURN NUMBER;
  FUNCTION UPDATE_LOG_YES_CHECK(
    P_CAR_ID IN NUMBER)
    RETURN NUMBER;
END GARAGE;

CREATE OR REPLACE
PACKAGE BODY GARAGE AS

  FUNCTION UPDATE_LOG_NO_CHECK(
    P_CAR_ID IN NUMBER)
    RETURN NUMBER AS
  BEGIN
    -- TODO: Implementation required for FUNCTION GARAGE.UPDATE_LOG_NO_CHECK
    INSERT INTO RDW_LOG ("ID", "CAR_ID", "MESSAGE", "TIMESTAMP") VALUES (RDW_LOG_SEQUENCE.NEXTVAL, P_CAR_ID, 'Inspection not requested', SYSDATE);
    RETURN P_CAR_ID;
  END UPDATE_LOG_NO_CHECK;

  FUNCTION UPDATE_LOG_YES_CHECK(
    P_CAR_ID IN NUMBER)
    RETURN NUMBER AS
  BEGIN
    -- TODO: Implementation required for FUNCTION GARAGE.UPDATE_LOG_YES_CHECK
    INSERT INTO RDW_LOG ("ID", "CAR_ID", "MESSAGE", "TIMESTAMP") VALUES (RDW_LOG_SEQUENCE.NEXTVAL, P_CAR_ID, 'Inspection requested', SYSDATE);
    RETURN P_CAR_ID;
  END UPDATE_LOG_YES_CHECK;

END GARAGE;