CREATE OR REPLACE TRIGGER APK_TRIGGER BEFORE
INSERT OR
UPDATE ON MAINTENANCEASSIGNMENT FOR EACH ROW DECLARE BLA NUMBER;
BEGIN
  IF :OLD.SPOTCHECK = :NEW.SPOTCHECK THEN
    RETURN;
  END IF;
  IF :OLD.SPOTCHECK    = 1 AND :NEW.SPOTCHECK = 0 THEN
    BLA               := GARAGE.UPDATE_LOG_DONE_CHECK(:OLD.CAR_ID);
  ELSIF :NEW.SPOTCHECK = 1 THEN
    BLA               := GARAGE.UPDATE_LOG_YES_CHECK(:OLD.CAR_ID);
  ELSIF :NEW.SPOTCHECK = 0 THEN
    BLA               := GARAGE.UPDATE_LOG_NO_CHECK(:OLD.CAR_ID);
  END IF;
END;