CREATE OR REPLACE TRIGGER APK_TRIGGER BEFORE
  INSERT OR
  UPDATE ON MAINTENANCEASSIGNMENT FOR EACH ROW DECLARE BLA NUMBER;
  BEGIN
    IF :OLD.SPOTCHECK = :NEW.SPOTCHECK THEN
      RETURN;
    END IF;
    IF :NEW.SPOTCHECK = 0 THEN
      DBMS_OUTPUT.put_line('BLA_0');
      BLA := GARAGE.UPDATE_LOG_NO_CHECK(:OLD.CAR_ID);
      DBMS_OUTPUT.put_line('YES');
    ELSIF :NEW.SPOTCHECK = 1 THEN
      DBMS_OUTPUT.put_line('BLA_1');
      BLA := GARAGE.UPDATE_LOG_YES_CHECK(:OLD.CAR_ID);
      DBMS_OUTPUT.put_line('NO');
    END IF;
  END;