package javaminor.al.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "RDWSteekproefWebService", targetNamespace = "http://steekproef.rdw/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface RDWSteekproefWebService {


    /**
     * Returns a true/false based on a "kenteken".
     *
     * @param kenteken license plate
     * @return returns java.lang.Boolean true/false at random
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "steekproef",
            targetNamespace = "http://steekproef.rdw/",
            className = "javaminor.al.service.client.Steekproef")
    @ResponseWrapper(localName = "steekproefResponse",
            targetNamespace = "http://steekproef.rdw/",
            className = "javaminor.al.service.client.SteekproefResponse")
    @Action(input = "http://steekproef.rdw/RDWSteekproefWebService/steekproefRequest",
            output = "http://steekproef.rdw/RDWSteekproefWebService/steekproefResponse")
    Boolean steekproef(
            @WebParam(name = "kenteken", targetNamespace = "")
            String kenteken);

}
